heatmiser:
  serial_port: socket://192.168.100.243:1024
  device_ids: 1-10
  device_names:
    1: Living Room
    2: Kitchen
    3: Dining Room
    4: Spare Room
    5: Office
    6: Bathroom
    7: Peter's Room
    8: Master Bedroom
    9: Matthew's Room

mqtt:
  broker: "192.168.11.7"
  port: 1883
  username: admin
  password: admin
  topic: homeassistant
